version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/log.log
    maxBytes: 1024
    backupCount: 3
  datefile:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    filename: logs_date/log.log
    when: midnight
    backupCount: 31
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console, file, datefile]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
